version: '3.8'

services:
  # 数据库服务
  db:
    image: mysql:5.7
    container_name: competition-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: springbootpx13e
      TZ: Asia/Shanghai
    ports:
      - "33306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - competition-net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  # 应用服务
  app:
    # 修改点：不再使用 build，直接拉取镜像
    # 注意：这里假设你的 Github 用户名是 0rooe，仓库名是 competition
    # 镜像名称必须全部小写
    image: ghcr.io/0rooe/competition:latest
    container_name: competition-app
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./upload:/app/upload
    depends_on:
      db:
        condition: service_healthy
    networks:
      - competition-net

networks:
  competition-net:
    driver: bridge
